# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textrank.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0etextrank.proto\x12\x08textrank\"\x17\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t2D\n\x0fTextRankService\x12\x31\n\tSummarize\x12\x11.textrank.Message\x1a\x11.textrank.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textrank_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_MESSAGE']._serialized_start = 28
    _globals['_MESSAGE']._serialized_end = 51
    _globals['_TEXTRANKSERVICE']._serialized_start = 53
    _globals['_TEXTRANKSERVICE']._serialized_end = 121
# @@protoc_insertion_point(module_scope)
